exports.CONNECT_STATE = 'CONNECT_STATE'
exports.CONNECT_COMMIT = 'CONNECT_COMMIT'

exports.DROP_FILE = 'DROP_FILE'

exports.VIDEO_SELECT = 'VIDEO_SELECT'
exports.PAUSE_FILE = 'PAUSE_FILE'
exports.RESUME_FILE = 'RESUME_FILE'
exports.REMOVE_QUEUE = 'REMOVE_QUEUE'
exports.REMOVE_QUEUES = 'REMOVE_QUEUES'
exports.SORT_QUEUE = 'SORT_QUEUE'
exports.VIDEO_TIMEUPDATE = 'VIDEO_TIMEUPDATE'
exports.VIDEO_CANPLAY = 'VIDEO_CANPLAY'
exports.VIDEO_SEEK = 'VIDEO_SEEK'
exports.VIDEO_PLAYED = 'VIDEO_PLAYED'
exports.VIDEO_PAUSED = 'VIDEO_PAUSED'
exports.VIDEO_ENDED = 'VIDEO_ENDED'

exports.CHANGE_LAYOUT = 'CHANGE_LAYOUT'
exports.CHANGE_MODE = 'CHANGE_MODE'
exports.CHANGE_OPACITY = 'CHANGE_OPACITY'
exports.SET_CLICKTHROUGH = 'SET_CLICKTHROUGH'
exports.RESIZE_PLAYER_MODE = 'RESIZE_PLAYER_MODE'

exports.OPEN_URL = 'OPEN_URL'

exports.RELOAD = 'RELOAD'
exports.QUIT = 'QUIT'
