exports.DROP_FILE = 'DROP_FILE'

exports.PLAY_FILE = 'PLAY_FILE'
exports.REMOVE_QUEUE = 'REMOVE_QUEUE'
exports.REMOVE_QUEUES = 'REMOVE_QUEUES'

exports.CONNECT_STATE = 'CONNECT_STATE'
exports.CONNECT_COMMIT = 'CONNECT_COMMIT'

exports.CHANGE_LAYOUT = 'CHANGE_LAYOUT'
exports.CHANGE_MODE = 'CHANGE_MODE'
exports.CHANGE_OPACITY = 'CHANGE_OPACITY'
exports.CHANGE_THROUGTH = 'CHANGE_THROUGTH'

exports.OPEN_URL = 'OPEN_URL'

exports.EXIT = 'EXIT'
