export default {
  CONNECT_STATE: 'CONNECT_STATE',
  CONNECT_COMMIT: 'CONNECT_COMMIT',
  CONNECT_SCREEN: 'CONNECT_SCREEN',

  DROP_FILE: 'DROP_FILE',

  VIDEO_SELECT: 'VIDEO_SELECT',
  PAUSE_FILE: 'PAUSE_FILE',
  RESUME_FILE: 'RESUME_FILE',
  REMOVE_QUEUE: 'REMOVE_QUEUE',
  CLEAR_QUEUES: 'CLEAR_QUEUES',
  SORT_QUEUE: 'SORT_QUEUE',
  VIDEO_TIMEUPDATE: 'VIDEO_TIMEUPDATE',
  VIDEO_CANPLAY: 'VIDEO_CANPLAY',
  VIDEO_SEEK: 'VIDEO_SEEK',
  VIDEO_PLAYED: 'VIDEO_PLAYED',
  VIDEO_PAUSED: 'VIDEO_PAUSED',
  VIDEO_ENDED: 'VIDEO_ENDED',

  CHANGE_MODE: 'CHANGE_MODE',
  CHANGE_OPACITY: 'CHANGE_OPACITY',
  SET_CLICKTHROUGH: 'SET_CLICKTHROUGH',
  RESIZE_PLAYER: 'RESIZE_PLAYER',

  OPEN_URL: 'OPEN_URL',
  URL_BACK: 'URL_BACK',
  URL_FORWARD: 'URL_FORWARD',
  URL_REFRESH: 'URL_REFRESH',

  RELOAD: 'RELOAD',
  RESET: 'RESET',
  QUIT: 'QUIT'
}
