export const CONNECT_STATE = 'CONNECT_STATE';
export const CONNECT_COMMIT = 'CONNECT_COMMIT';
export const CONNECT_SCREEN = 'CONNECT_SCREEN';

export const DROP_FILE = 'DROP_FILE';

export const VIDEO_SELECT = 'VIDEO_SELECT';
export const PAUSE_FILE = 'PAUSE_FILE';
export const RESUME_FILE = 'RESUME_FILE';
export const REMOVE_QUEUE = 'REMOVE_QUEUE';
export const CLEAR_QUEUES = 'CLEAR_QUEUES';
export const SORT_QUEUE = 'SORT_QUEUE';
export const VIDEO_TIMEUPDATE = 'VIDEO_TIMEUPDATE';
export const VIDEO_CANPLAY = 'VIDEO_CANPLAY';
export const VIDEO_SEEK = 'VIDEO_SEEK';
export const VIDEO_PLAYED = 'VIDEO_PLAYED';
export const VIDEO_PAUSED = 'VIDEO_PAUSED';
export const VIDEO_ENDED = 'VIDEO_ENDED';

// Settings
export const SET_MODE = 'SET_MODE';
export const SET_OPACITY = 'SET_OPACITY';
export const SET_HIDE_ON_TASKBAR = 'SET_HIDE_ON_TASKBAR';
export const SET_CLICKTHROUGH = 'SET_CLICKTHROUGH';
export const TOGGLE_RESIZE = 'TOGGLE_RESIZE';
export const START_RESIZE = 'START_RESIZE';
export const END_RESIZE = 'END_RESIZE';
export const SET_FULLSCREEN = 'SET_FULLSCREEN';
export const TOGGLE_SETTINGS = 'TOGGLE_SETTINGS';
export const OPEN_WEBVIEW = 'OPEN_WEBVIEW';
export const CLOSE_WEBVIEW = 'CLOSE_WEBVIEW';

// Browser Actions
export const BROWSER_VIEW_EVENT = 'BROWSER_VIEW_EVENT';
export const SET_URL = 'SET_URL';
export const BROWSER_RELOAD = 'BROWSER_RELOAD';
export const BROWSER_BACK = 'BROWSER_BACK';
export const BROWSER_FORWARD = 'BROWSER_FORWARD';
export const BROWSER_CAN_GO_BACK = 'BROWSER_FORWARD';
export const BROWSER_CAN_GO_FORWARD = 'BROWSER_FORWARD';

export const RESET = 'RESET';
export const QUIT = 'QUIT';

export const WINDOW_TRANSPARENT_ON = 'WINDOW_TRANSPARENT_ON';
export const WINDOW_TRANSPARENT_OFF = 'WINDOW_TRANSPARENT_OFF';

// VideoList
export const VIDEO_LIST_TOGGLE = 'VIDEO_LIST_TOGGLE';
export const VIDEO_LIST_ADD_FILES = 'VIDEO_LIST_ADD_FILE';
export const VIDEO_VIEW_EVENT = 'VIDEO_VIEW_EVENT';
export const VIDEO_BACK = 'VIDEO_BACK';
export const VIDEO_PLAY = 'VIDEO_PLAY';
export const VIDEO_PAUSE = 'VIDEO_PAUSE';
export const VIDEO_FORWARD = 'VIDEO_FORWARD';

// Video Monitor
export const SET_VIDEO_SOURCE = 'SET_VIDEO_SOURCE';
